### ISSUE TITLE
How to use the MODNet demo?

### ISSUE THREAD

**Issue by benbro** [w-okada/image-analyze-workers#30]
The [MODNet demo](https://github.com/w-okada/image-analyze-workers/tree/master/010demo_modnet-worker-js-demo) is missing from the [README](https://github.com/w-okada/image-analyze-workers/blob/master/README.md).
How is the [wasm model](https://github.com/w-okada/image-analyze-workers/blob/master/010demo_modnet-worker-js-demo/public/tfjs-backend-wasm.wasm) created? Is there a WebGL version?
I've tried to clone and run the demo locally but not sure what URL do load in the browser.

**Comment by w-okada** [comment]
I have not yet solved how to use MODNet.
Currently no idea.

**Comment by PINTO0309** [comment]
There was a bug in the model committed three months ago, so it was fixed and re-committed at the end of February.

**https://drive.google.com/file/d/1Y6B6l72hib9t5ammT-7ya-muBzRKZ7xq/view?usp=sharing**
**https://github.com/PINTO0309/PINTO_model_zoo/issues/75#issuecomment-787097482**
![image](https://user-images.githubusercontent.com/33194443/112843662-c7408a80-90dd-11eb-9e44-e47d80742d16.png)

**Comment by benbro** [comment]
@w-okada does the new model helps? I still don't understand how to use it with tfjs,

**Comment by w-okada** [comment]
I tried. But very slow.

**Comment by benbro** [comment]
Can you please explain how to test the code?
I'm sure the community can help with the performance and model translation to tfjs issues.

**Comment by w-okada** [comment]
yes please wait. Above comment is just a quick report.
I'll commit the source later.

**Comment by benbro** [comment]
@w-okada thank you for the demo.
Does the demo use WebAssembly or WebGL? Maybe [WebSeembly SIMD](WebAssembly SIMD) in Chrome 91 will help?
I suggest setting onLocal to false by default in the demo because it makes the browser unresponsive.
What does the strict parameter do?
What's the difference between model 16 and 32?

@PINTO0309 do you have idea why the worker demo result doesn't look as good as the original demo? Is there something wrong in the model translation or use?
Input:
![test](https://user-images.githubusercontent.com/75841/113274833-ccbcf100-92e6-11eb-914e-1b1e53d4a6a4.jpg)
Result with the [worker demo](https://github.com/w-okada/image-analyze-workers/tree/master/010demo_modnet-worker-js-demo):
![test1](https://user-images.githubusercontent.com/75841/113274861-d21a3b80-92e6-11eb-9ac6-e904dfaf63d6.png)
Result with the original [demo](https://gradio.app/g/modnet):
![test2](https://user-images.githubusercontent.com/75841/113274891-d9414980-92e6-11eb-9bfd-5cb09e478246.png)

**Comment by w-okada** [comment]
> Does the demo use WebAssembly or WebGL? Maybe WebSeembly SIMD in Chrome 91 will help?
The demo uses WebGL Generally wasmSIMD is slower than WebGL.

> What does the strict parameter do?
None. I forgot to erase it

> What's the difference between model 16 and 32?
Float16 and Float32.

**Comment by w-okada** [comment]
@benbro 

@PINTO0309 have created the low resolution models (256x256, 192x192, 128x128). They are much faster than the original one. But A little less quality. Please try with my demo page.

In my environment (with GTX 1660),
512x512:500ms
256x256:60ms
128x128:30ms

**Comment by benbro** [comment]
Thank you for the new models, as you said they are much faster but quality isn't good.

**Comment by PINTO0309** [comment]
@benbro 
Perhaps this is not the right place to discuss this, but U^2-Net may also be promising.
https://github.com/xuebinqin/U-2-Net
https://github.com/w-okada/image-analyze-workers#u2-net-portrait-drawing
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/061_U-2-Net

**Comment by benbro** [comment]
@PINTO0309 is there a U^2-Net demo for background matting instead of portrait drawing?

**Comment by w-okada** [comment]
Maybe there is no javascript demo. I think it is also slow, because the portrait drawing model is so slow and the background matting is basically the same model as the portrait one.

Can I clonse this issue?

**Comment by benbro** [comment]
All models in the MODNet demo gives me bad result compared with the original project demo. Something is probably broken with the model translation.
Thank you for the help. You can close this issue.

**Comment by benbro** [comment]
This might be interesting:
https://github.com/Volcomix/virtual-background#ml-kit-selfie-segmentation
https://github.com/Volcomix/virtual-background/issues/2
https://developers.google.com/ml-kit/vision/selfie-segmentation
https://developers.google.com/ml-kit/images/vision/selfie-segmentation/selfie-model-card.pdf

**Comment by w-okada** [comment]
Wow! Very insteresting!!

First of all, I'll download and save model-card!! :P

**Comment by w-okada** [comment]
@benbro
Thanks, I added selfie segmentation model in my zoo.

**Comment by benbro** [comment]
Thank you for adding a demo so fast.

I'm getting bad result with this video even with the 256x256 model. Any way to improve it?
https://www.shutterstock.com/video/clip-1048026787-businessman-talking-camera-making-conference-business-call

What's the difference between the original model and pinto_x models? Should I expect better quality or performance?
Does it make sense to use a process size larger then the model size? (300x300 and 512x512)
Padding has no visible effect.
What does the Strict option do?
-

**Comment by w-okada** [comment]
> What's the difference between the original model and pinto_x models?
these model from  https://github.com/PINTO0309/PINTO_model_zoo
I have no idea if we can expect improvement. But in my demo there is no effect.

> Does it make sense to use a process size larger then the model size? (300x300 and 512x512)
In my demo, resizing image is done in wasm with opencv. "Interpolation" is used for the interpolation.
If you want to use opencv to resize, you set the different size from model output size. If you want to resize with HTML Canvas, you need not.

> Padding has no visible effect.
Yes. Just I forgot to erase it.

> What does the Strict option do?
If you enable strict, input image to model is kept and output from model is applied to it
If not, output from model is applied to current frame image.
Which is used depends on your thought about the time lag of processing model.

**Comment by benbro** [comment]
Thanks!

**Comment by PINTO0309** [comment]
In addition, I converted Selfie Segmentation to various models and committed them.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/109_Selfie_Segmentation
